### ISSUE TITLE
Release Management

### ISSUE THREAD

**Issue by feryardiant** [creasico/laravel-project#36]
Issue ini tidak hanya mencakup bagaimana tata kelola penomoran versi (versioning) semata namun juga proses distribusi / deployment secara umum baik untuk shared project open source, client project maupun di product kita sendiri, antara lain : 

### General Projects
- Otomatis generate `CHANGELOG.md` dan mencatat setiap perubahan atau commit di tiap versi nya.
- Otomatis membuat [github release](https://docs.github.com/en/repositories/releasing-projects-on-github) setiap kali push tag
- Otomatis deploy ke production tiap kali ada release untuk project app
### Client' Projects
- Otomatisasi integrasi ke Jira jika memungkinkan
- Generate `CHANGELOG.md` yang berisi summary atas tasks yang dikerjakan
### Our Products
- _Notify_ pengguna baik pada aplikasi maupun email jika sudah memungkinkan

## Workflows

Dalam hal ini kita gunakan convention yang sudah ada dan banyak digunakan aja biar gak ribet mikir lagi, selain itu biasanya sudah ada tools yang bisa kita pakai untuk menggunakan convention tersebut.

Seperti yang sudah saya terapkan selama ini walaupun mungkin bukan yang terbaik atau mungkin juga sudah ada yang lebih baik lagi saat ini, kita perlu gali lagi lebih lanjut. Yaitu dengan menggunakan tool antara lain : 
- [**Conventional Commit**](https://www.conventionalcommits.org/en/v1.0.0) : Seperti yang kita ketahui bahwa ini adalah default format commit message di setiap project di creasico. Tujuan utama nya tidak lain adalah untuk mempermudah proses otomasi pada tahap-tahap berikutnya.

  Dengan menggunakan default [`config-conventional`](https://www.npmjs.com/package/@commitlint/config-conventional) hal yang masih jadi PR kita bersama adalah `SCOPE` dari commit tersebut.

- **Version Bump** : Saat ini kita menggunakan [`standard-version`](https://www.npmjs.com/package/standard-version) dimana tool ini (setidaknya untuk saat ini) cukup bisa diandalkan untuk salah satu poin yang ada di **General Project** diatas.

  Dan tiap kali ada perubahan versi si `standard-version` ini akan meng-update field `version` yang ada di file `package.json`, yang mana itu adalah tempat satu-satunya untuk menyimpan versi terakhir dari masing-masing repo. Apakah bisa diubah? jawabannya bisa! Tapi untuk saat ini biarkan default seperti itu dulu, kita diskusikan lagi ini nanti. Selain itu, saya prefer definisi di 1 tempat dan bisa digunakan di banyak tempat.

  Nah! dari situ, kendala saat ini adalah penggunaanya masih belum terimplementasi dengan baik khususnya di backend. Ini nanti ada kaitannya juga dengan [release management di sentry](https://docs.sentry.io/product/releases/).

- **Continous Delivery** : Kebetulan siang ini kita handle proses deployment salah satu project client kita ke production. Di diskusi tadi saya memutuskan : 

  - Gunakan `tag` untuk deploy ke `production`, dan
  - Gunakan `branch` untuk deploy ke `staging`

  Dimana untuk handle task tersebut perlu konfigurasi github actions yang berbeda. Semua berjalan sesuai harapan, namun masih ada ruang untuk improvement agar proses ini bisa lebih komprehensive.

**Comment by sakukode** [comment]
Dari deskripsi issue di atas, apa berarti ada perbedaan `CHANGELOG.md` utk `Our Products` dengan `Client Projects`, dimana kalau untuk `Client Projects` lebih ke summary tasks. pada commit berikut https://github.com/creasico/laravel-project/pull/55/commits/05f14bde71a5e488dc456e2f2b81f32356bf5aa6 dijelaskan jika github hanya bisa mendapatkan informasi dari PR's title. Nah bagaimana caranya misal jika kita ingin menyisipkan issue ID (jira) yang mungkin nantinya bisa diintegrasikan dengan jira, apa artinya kita perlu menuliskan issue ID pada commit message atau cukup menuliskan pada PR's title?

**Comment by feryardiant** [comment]
> apa berarti ada perbedaan `CHANGELOG.md` utk `Our Products` dengan `Client Projects`, dimana kalau untuk `Client Projects` lebih ke summary tasks.

Yap! dan ini masih perlu kita godok lagi bagaimana baiknya.

> Nah bagaimana caranya misal jika kita ingin menyisipkan issue ID (jira) yang mungkin nantinya bisa diintegrasikan dengan jira

Aku sempet baca sekilas dokumentasi di Jira, terkait integrasi ke GitHub. Di Jira ada beberapa cara dengan nama branch, PR title, PR comment, ataupun commit message. Read:

- https://support.atlassian.com/jira-software-cloud/docs/reference-issues-in-your-development-work/
- https://support.atlassian.com/jira-software-cloud/docs/process-issues-with-smart-commits/

Tapi hanya berlaku untuk project yang jenis nya "Software Project", bukan "Business Project". Untuk "Business Project" ada app di Jira yang bisa membantu dan udah kita install di project client kita sekarang. Tapi aku liat masih harus nyantumin link PR secara manual.
