### ISSUE TITLE
Dependabot gak bisa baca github secrets

### ISSUE THREAD

**Issue by feryardiant** [creasico/laravel-project#54]
Dari beberapa PR dependabot malem ini (khususnya setelah aku bikin config nya di #40), semua CI di PR tersebut bermasalah. Setelah tak pelajari lagi ternyata issue nya karna dependabot gak bisa akses github secrets. Hal tersebut di konfirmasi dengan : 

- https://github.com/dependabot/dependabot-core/issues/3253
- https://github.com/orgs/community/discussions/30588

## Hipotesa
- Berdasarkan [post ini](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) disebutkan bawa workflow trigger nya perlu diganti dari `pull_request` jadi `pull_request_target`
- Opsi lain yang mungkin diterapkan adalah dengan menggunakan field [`token`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-private-registries) di `dependabot.yml`, tapi untuk saat ini saya masih belum yakin apakah token ini juga berlaku untuk composer package yang ada di github repo. Sementara di dokumentasinya hanya menyebutkan private composer registry.

**Comment by feryardiant** [comment]
Bangun tidur langsung baca-baca lagi link yang aku cantumin diatas dan kesimpulan yang aku dapet sementara ini adalah konyol, gimana gak, dalam hal ini keliatan sama sekali gak ada celah sama sekali kecuali dari sisi kita yang "intentionally" bikin workflows "vunerable".

Dan aku sama sekali gak dapet poin nya ketika mereka [bilang](https://github.com/orgs/community/discussions/30588#discussioncomment-3659994)

> Security is important for us, therefore we applauded the change made in https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-797125425 where bots lost access to secrets by default to prevent eg. npm based attacks.
>
> We have a lot (and I mean a lot) of secrets that we do not give access to bots (dependabot, renovate) and our workflow for all PRs opened by those, was (up until recently) to review PR and re-run their build by someone from the team.

Ok, dan [disini](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/) mereka bilang

> If your workflow needs to have a write token or access to secrets, you can use the [`pull_request_target`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target) event;

Tapi [disini](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) mereka juga bilang

> There exists a potentially dangerous misuse of the `pull_request_target` _workflow trigger_ that may lead to malicious PR authors (i.e. attackers) being able to obtain repository write permissions or stealing repository secrets.

Dari situ mereka menyarankan untuk mix workflow dimana perlu ada job tersendiri untuk memastikan bahwa workflow tersebut "aman" yaitu workflow dengan trigger `pull_request` untuk cek PR dan output berupa label, misal "safe" setelah pr tersebut diberi label github akan trigger workflow `pull_request_target`. Ini buat aku terkesan kayak **"Ok, PR ini kayaknya aman, silakan pintunya dibuka semua"**.

Nah waktu aku coba cek repo settings, ternyata dependabot bisa set secrets tersendiri. Yang intinya adalah kita bisa kasih dependabot akses ke secret tertentu agar workflow kita bisa jalan.

![Screenshot 2023-10-29 at 00 57 45](https://github.com/creasico/laravel-project/assets/508665/7dd74bde-010a-4b35-b97d-601156c96dd0)

Ok, berarti kita bisa **"ngasih kunci tertentu"** biar dependabot **"bisa masuk"**.

Buat aku 2 opsi tersebut konyol semua, gimana gak? Kita harus kompromi dengan "extra steps" di workflow kita atau kompromi untuk nulis ulang `secrets` yang sama di tempat yang berbeda untuk tujuan yang sama atas alasan "keamanan" yang kalaupun kita terapin itu gak serta merta kita aman juga.

Kesimpulan ku dari issue ini adalah, pihak github secara tidak langsung "lepas tangan" jika repository kita "vunerable".

asu kan?

**Comment by feryardiant** [comment]
@feryardiant Format release notes, coba karo woco commit ku dek kene pak

**Comment by sakukode** [comment]
Apa bedanya event `pull_request` dengan `pull_request_target` pada option github workflow? (sudah coba referensi tapi masih belum terlalu yakin ).

**Comment by sakukode** [comment]
Aku ambil contoh masalah vulnerability dari artikel di atas. Jika vulnerability itu datangnya dari dependency suatu repo (baik itu dari ekosistem `composer` maupun `npm`).  Aku juga belum punya pengalaman terkait ini karena belum pernah bikin package yang sampai dirilis ke publish lewat composer/npm. Cuma apakah dari kedua package manager di atas itu tidak ada semacam pengecekan keamanan pada suatu package apakah mengandung malicious code atau tidak?

**Comment by sakukode** [comment]
Dan balik lagi ke issue di atas, dimana yang aku tangkap, Kita bisa ngasih akses tertentu pada PR yang dibuat oleh dependabot jika sudah memastikan PR itu aman dan menjalankannya pada workflow? Cuma aku sendiri belum nangkep, bagaimana mekanisme untuk memastikan kalau PR itu aman (kesannya kaya malah butuh ekstra step aja)? Dari komennya sampean @feryardiant  Itu terkesan seperti hal yang sia-sia, jika GitHub tetap lepas tangan atau tidak bisa memastikan kalau repository kita aman dari vulnerability.

**Comment by sakukode** [comment]
Solusi yang bisa kita lakukan seperti apa? Apakah artinya perlu melakukan `code review` secara manual juga terhadap PR dari dependabot ini untuk memastikan kalau PR tsb `safe`?

**Comment by feryardiant** [comment]
Singkatnya untuk `pull_request` github gak ngasih bot akses ke repo `secrets`, sedangkan `pull_request_target` ngasih, itu aja sih sepaham ku.

> Aku ambil contoh masalah vulnerability dari artikel di atas. Jika vulnerability itu datangnya dari dependency suatu repo

Nah ini jg yang aku masih heran, ini terkesan kayak dengan `pull_request_target` ini kita "ngebuka semua pintu" ketika ada bot masuk dari depan tapi yang vulnerable ini sebenernya pintu belakang. Yang mana si bot itu sendiripun gak punya control atas hal itu.

> Cuma apakah dari kedua package manager di atas itu tidak ada semacam pengecekan keamanan pada suatu package apakah mengandung malicious code atau tidak?

NPM & Packagist setau ku ada audit nya jg.

> bagaimana mekanisme untuk memastikan kalau PR itu aman (kesannya kaya malah butuh ekstra step aja)

Sependapat

> Apakah artinya perlu melakukan `code review` secara manual juga terhadap PR dari dependabot ini untuk memastikan kalau PR tsb `safe`?

Ini wasting time sekali.

> Solusi yang bisa kita lakukan seperti apa?

IMO, daripada kita review apa yang dilakukan si dependabot, lebih baik kita pastiin kita paham package apa yang kita gunakan sebagai dependensi. Github sendiri udah ada tab Security di tiap repo nya, itu bisa jadi salah satu opsi untuk mastiin dependency yang kita gunakan "aman". Baik itu direct maupun indirect dependency.

**Comment by feryardiant** [comment]
Dan diketahui ternyata trigger `pull_request_target` ini hanya jalan di default branch, bukan di branch PR nya. See creasico/laravel-nusa#46 and [it's ci](https://github.com/creasico/laravel-nusa/actions/runs/6788202638/job/18452663298?pr=46#step:7:16).

Ini konyol sih 🤦🏻‍♂️
